# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even tools like Pandas are built around the NumPy array.

Here we see several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
 

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let's see some useful array attributes.

We'll start by defining three random arrays: 
1. a one-dimensional array
2. two-dimensional array
3. three-dimensional array

We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the `same random arrays` are generated each time this code is run:

Each array has attributes: 
  -  ``ndim`` (the number of dimensions)
  - ``shape`` (the size of each dimension)
  -  ``size`` (the total size of the array)

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array, 3 elements,  each has 4 members
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array, Three arrays, each one with 4 elements, each has 5 members

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
print('x1 ndim: ', x1.ndim)
print('x1 shape:', x1.shape)
print('x1 size: ', x1.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
print('x2 ndim: ', x2.ndim)
print('x2 shape:', x2.shape)
print('x2 size: ', x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [6]:
print('x3 ndim: ', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size: ', x3.size) #np.size(x3)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [7]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

Another useful attribute is the ``dtype``, the data type of the array. 

In [8]:
print('dtype:', x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [9]:
print('itemsize {} bytes'.format(x3.itemsize))
print('nbytes {} bytes'.format(x3.nbytes))

itemsize 8 bytes
nbytes 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

In [10]:
print('itemsize x size\t:', x3.itemsize*x3.size)
print('nbytes \t\t:', x3.nbytes)

itemsize x size	: 480
nbytes 		: 480


## Array Indexing: Accessing Single Elements

Same as Python's standard list indexing, indexing in NumPy also can be done. 

In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [12]:
x1[0]

5

To index from the end of the array, you can use negative indices:

In [13]:
x1[-1]

9

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0, 0]

3

In [16]:
x2[2, 0]

1

Values can also be modified using any of the above index notation:

In [17]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
> If you attempt to insert a floating-point value to an integer array, the value will be silently truncated. 

Don't be caught unaware by this behavior!

In [18]:
import math

In [19]:
x1[0] = math.pi  # decimals will be truncated, since x1 is of int. 
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.

The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.

We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [22]:
x[5:]  # elements from index 5 to the end

array([5, 6, 7, 8, 9])

In [23]:
x[4:7]  # from 4th element to 7th (excluded)

array([4, 5, 6])

In [24]:
x[::2]  # from begining to the end, every other element

array([0, 2, 4, 6, 8])

In [25]:
x[1::2]  # every other element, starting at index 1 to the end

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [26]:
x[::-1]  # From end to the begining, all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [28]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [29]:
x2[:2, :3]  # from the begining two elements. Each has three members from the begining

array([[12,  5,  2],
       [ 7,  6,  8]])

In [30]:
x2[:, ::2]  # all elements, every other members in each elements

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [31]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [32]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [33]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [34]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [35]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.

This is one area in which NumPy array slicing differs from Python list slicing: 
> In lists, slices will be copies.

Consider our two-dimensional array from before:

In [36]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2 \times 2$ subarray from this:

In [37]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [38]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [39]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [40]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [41]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [42]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.

For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [43]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [44]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [45]:
print('shape \t: ',x.shape)
print('First element \t:', x[0])

shape 	:  (4,)
First element 	: 1


In [46]:
# row vector via reshape
y = x.reshape((2, 2)) # It is two dimensional now.
y 

array([[1, 2],
       [3, 4]])

In [47]:
print('shape \t: ',y.shape)
print('First element \t:', y[0])

shape 	:  (2, 2)
First element 	: [1 2]


In [48]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3, 4]])

In [49]:
x

array([1, 2, 3, 4])

In [50]:
# column vector via reshape
x.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [51]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines:
- ``np.concatenate`` : takes a tuple (list) of arrays as its first argument
-  ``np.vstack`` & 
-  ``np.hstack``

In [52]:
x = np.array([1, 2, 3])
y = np.array([13, 12, 11])

In [53]:
np.concatenate([x, y])

array([ 1,  2,  3, 13, 12, 11])

You can also concatenate more than two arrays at once:

In [54]:
z = [97, 98, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3 13 12 11 97 98 99]


It can also be used for two-dimensional arrays:

In [55]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [56]:
grid.shape

(2, 3)

In [57]:
# concatenate along the first axis
new_grid = np.concatenate([grid, grid])
new_grid

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
new_grid.shape

(4, 3)

Concatenate along the second axis (zero-indexed): 

In [59]:
np.concatenate([grid, grid], 
               axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the functions: 
- ``np.vstack`` (vertical stack) & 
-  ``np.hstack`` (horizontal stack) 

In [60]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]
                 ])

In [61]:
print(x)
print(grid)

[1 2 3]
[[9 8 7]
 [6 5 4]]


Vertically stack the arrays: 

In [62]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

Horizontally stack the arrays: 

In [63]:
y = np.array([[99],
              [99]])

In [64]:
print(y)
print(grid)

[[99]
 [99]]
[[9 8 7]
 [6 5 4]]


In [65]:
np.hstack([y, grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

Similary, ``np.dstack`` will stack arrays along the third axis.

In [66]:
a = np.array((1,2,3))
b = np.array((12,13,14))

In [67]:
print(a)
print(b)

[1 2 3]
[12 13 14]


In [68]:
np.dstack((a,b)) # it's of 3D. 

array([[[ 1, 12],
        [ 2, 13],
        [ 3, 14]]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions : 
- ``np.split``
- ``np.hsplit`` & 
- ``np.vsplit``

For each of these, we can pass a list of indices giving the split points:

In [69]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3, x4 = np.split(x, [2, 3, 5]) #split on positions 2, 3, & 5
print( x1, '\n',x2, '\n',x3, '\n', x4)

[1 2] 
 [3] 
 [99 99] 
 [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [70]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
top, bottom = np.vsplit(grid, [2])
print(top)
print(bottom)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [72]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

In [73]:
x = np.arange(16).reshape(2, 2, 4) # Two members, In each, two elements. Each has 4 elements
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [74]:
np.dsplit(x, 4) #split to 4 arrays of equal size. 

[array([[[ 0],
         [ 4]],
 
        [[ 8],
         [12]]]), array([[[ 1],
         [ 5]],
 
        [[ 9],
         [13]]]), array([[[ 2],
         [ 6]],
 
        [[10],
         [14]]]), array([[[ 3],
         [ 7]],
 
        [[11],
         [15]]])]

<!--NAVIGATION-->
< [Previous](https://github.com/Egade/ClassNotes/blob/main/021_read_iloc_unique_groupby.ipynb) 
| [Toc](https://github.com/Egade/ClassNotes) 
| [Next](nex) >